name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install core dependencies
      run: pip install -r requirements.txt

    - name: Install development dependencies
      run: pip install -r requirements-dev.txt

    - name: Run flake8
      run: flake8 .

    - name: Run pylint
      run: |
        pylint decision_tree.py
        pylint neural_network.py

    - name: Execute scripts
      run: |
        python decision_tree.py
        python neural_network.py

    - name: Commit and push changes
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        if ! git diff --quiet || ! git diff --staged --quiet; then
          git add .
          git commit -m "Update files"
          git push --force
        fi
